const constants = {
    "Call Us Free": "Call Us Free",
    18003094005: "18003094005",
    Gurgon: "Gurgon",
    "My Account": "My Account",
    My_Account_Arr: ["Login", "Register", "Sell", "Partner Dashboard"],
    "My Cart": "My Cart",
    "You have no items in your shopping cart":
      "You have no items in your shopping cart",
    "E TWO WHEELERS": "E TWO WHEELERS",
    "E THREE WHEELERS": "E THREE WHEELERS",
    "ELECTRIC CAR": "ELECTRIC CAR",
    "ELECTRIC MASS MOBILITY": "ELECTRIC MASS MOBILITY",
    "NEWS & REVIEWS": "NEWS & REVIEWS",
    "EV SERVICES": "EV SERVICES",
    "ABOUT US": "ABOUT US",
    FRANCHISE: "FRANCHISE",
    "SHOP BY ELECTRIC VEHICLE": "SHOP BY ELECTRIC VEHICLE",
    "CHOOSE FROM POPULAR ELECTRIC VEHICLES":
      "CHOOSE FROM POPULAR ELECTRIC VEHICLES",
    "SHOP BY BRANDS": "SHOP BY BRANDS",
    "SELECT FROM WIDE RANGE OF EV BRANDS": "SELECT FROM WIDE RANGE OF EV BRANDS",
    "SELECT YOUR ELECTRIC VEHICLE": "SELECT YOUR ELECTRIC VEHICLE",
    "TOP OFFERS": "TOP OFFERS",
    "CHOOSE FROM THE VARIETY OF TOP PRODUCTS & SERVICES OFFERED BY US":
      "CHOOSE FROM THE VARIETY OF TOP PRODUCTS & SERVICES OFFERED BY US",
    "BEST SELLERS": "BEST SELLERS",
    "CHOOSE FROM BEST SELLING ELECTRIC BIKES & CYCLES":
      "CHOOSE FROM BEST SELLING ELECTRIC BIKES & CYCLES",
    NEWS: "NEWS",
    COMPARISION: "COMPARISION",
    "CHOOSE FROM BEST SELLING ELECTRIC BIKES & CYCLES":
      "CHOOSE FROM BEST SELLING ELECTRIC BIKES & CYCLES",
    "VIEW COMPARISION": "VIEW COMPARISION",
    "NEW ARRIVALS": "NEW ARRIVALS",
    "CHOOSE FROM OUR LATEST COLLECTION OF ELECTRIC BIKES, SCOOTERS & CYCLES":
      "CHOOSE FROM OUR LATEST COLLECTION OF ELECTRIC BIKES, SCOOTERS & CYCLES",
    "GUIDES & TUTORIALS": "GUIDES & TUTORIALS",
    "GET INSIGHTS FROM OUR EXPERTS": "GET INSIGHTS FROM OUR EXPERTS",
    "JOIN OUR COMMUNITY": "JOIN OUR COMMUNITY",
    "SUBSCRIBE TO OUR NEWSLETTERS": "SUBSCRIBE TO OUR NEWSLETTERS",
    "Join the community of Green Warriors with for exciting awards, cash backs, latest news, EV maintenance tips, exclusive discounts and much more.":
      "Join the community of Green Warriors with for exciting awards, cash backs, latest news, EV maintenance tips, exclusive discounts and much more.",
    "CUSTOMER REVIEWS": "CUSTOMER REVIEWS",
    "ABOUT EVKHARIDO": "ABOUT EVKHARIDO",
    "EVKharido is committed to accelerate the pace of adopting green energy by making it easy for customers to migrate from conventional fossil fuel powered ICE’s to EV’s running on clean, green, sustainable energy sources. Our mission is to be a one-stop-shop for all things EV for migrating customers and first time EV owners, to enable them to make informed decisions, and empower them to purchase the EV best suited to their needs with one easy click.":
      "EVKharido is committed to accelerate the pace of adopting green energy by making it easy for customers to migrate from conventional fossil fuel powered ICE’s to EV’s running on clean, green, sustainable energy sources. Our mission is to be a one-stop-shop for all things EV for migrating customers and first time EV owners, to enable them to make informed decisions, and empower them to purchase the EV best suited to their needs with one easy click.",
    "QUICK LINKS": "QUICK LINKS",
    "Terms & Conditions": "Terms & Conditions",
    "Privacy Policy": "Privacy Policy",
    "Pricing Policy": "Pricing Policy",
    "Exchange Policy": "Exchange Policy",
    "Shipping Policy": "Shipping Policy",
    Sitemap: "Sitemap",
    "Why Ev / Benefits of Ev": "Why Ev / Benefits of Ev",
    FAQs: "FAQs",
    Brands: "Brands",
    "Partner with Us": "Partner with Us",
    "About Us": "About Us",
    "Contact Us": "Contact Us",
    "Work With Us": "Work With Us",
    "Savings Calculator": "Savings Calculator",
    "© 2022 Shop My EV India Pvt Ltd . All Rights Reserved.":
      "© 2022 Shop My EV India Pvt Ltd . All Rights Reserved.",
    "STAY CONNECTED": "STAY CONNECTED",
    SUBSCRIBE: "SUBSCRIBE",
    base_url: "https://evkharido.com",
    Banner1: "media/wysiwyg/slider/cycle_banner_1_.jpg",
    Banner2: "media/wysiwyg/slider/WE_ARE_OPEN_NOW_3.jpg",
    Banner3: "media/wysiwyg/slider/scooter_banner_4_.jpg",
    "ELECTRIC CAR": "media/catalog/category/1_copy.jpg",
    "ELECTRIC SCOOTER": "media/catalog/category/3_copy_3.jpg",
    "ELECTRIC CYCLE": "media/catalog/category/2_copy1.jpg",
    "ELECTRIC BIKE": "media/catalog/category/4_copy1.jpg",
    "ELECTRIC MOPED": "media/catalog/category/5_copy_2.jpg",
    "ELECTRIC BUS": "media/catalog/category/6_copy_1.jpg",
    "ELECTRIC 3 WHEELER": "media/catalog/category/7_copy1_1.jpg",
    "ELECTRIC E RIKSHAW": "media/catalog/category/8_copy_1.jpg",
    brand1: "media/wysiwyg/jpeg_logo.jpg",
    brand2: "media/wysiwyg/e-scooter/2.jpg",
    brand3: "media/wysiwyg/e-scooter/3.jpg",
    brand4: "media/wysiwyg/e-scooter/12.jpg",
    brand5: "media/wysiwyg/rbseva_logo.jpg",
    brand6: "media/wysiwyg/e-scooter/9.jpg",
    brand7: "media/wysiwyg/e-cycle/13.jpg",
    brand8: "media/wysiwyg/e-cycle/14.jpg",
    brand9: "media/wysiwyg/e-scooter/1.jpg",
    brand10: "media/wysiwyg/e-cycle/17.jpg",
    brand11: "media/wysiwyg/sturdy_bikes_logo.jpg",
    brand12: "media/wysiwyg/kionic_mobility.jpg",
    brand13: "media/wysiwyg/e-scooter/10.jpg",
    brand14: "media/wysiwyg/e-cycle/21.jpg",
    brand15: "media/wysiwyg/e-scooter/6.jpg",
    brand16: "media/wysiwyg/e-cycle/23.jpg",
    top_offers1: "media/wysiwyg/testride.jpg",
    top_offers2: "media/wysiwyg/exchange_banner.jpg",
    top_offers3: "media/wysiwyg/Banner_4_copy.jpg",
    top_offers4: "media/wysiwyg/Accessories.jpg",
    top_offers5: "media/wysiwyg/emi_bonus_2.jpg",
    bestSeller1:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/r/b/rbseva_legend__images_reviews__price__range__charging_time__accessories1.jpg",
    bestSellers2:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/v/i/vijanta_arka_images_reviews_price_range_charging_time_accessories_2_.jpg",
    bestSellers3:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/z/e/zelio_eeva_images_reviews_price__range__charging_time__accessories_black_colour.jpg",
    bestSellers4:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/g/_/g_kon_roadies_vs__images_reviews__price__range__charging_time__accessoriess_copy1.jpg",
    news1: "media/magefan_blog/feature_216.jpg",
    news2: "media/magefan_blog/feature_219.jpg",
    news3: "media/magefan_blog/feature_214.jpg",
    comparision11:
      "media/catalog/product/cache/55b9373a2aa8f64c6d5d3c78cc654110/e/v/evex_sprint_m2__images_reviews_price__range__charging_time__accessories_copy1.jpg",
    comparision12:
      "media/catalog/product/cache/55b9373a2aa8f64c6d5d3c78cc654110/e/v/evex_sprint_m2__images_reviews_price__range__charging_time__accessories_copy1.jpg",
    comparision21:
      "media/catalog/product/cache/55b9373a2aa8f64c6d5d3c78cc654110/p/o/powertron_crampo_images_reviews_price_range_charging_time_accessories.jpg",
    comparision22:
      "media/catalog/product/cache/55b9373a2aa8f64c6d5d3c78cc654110/v/i/vijanta_arka_images_reviews_price_range_charging_time_accessories_2_.jpg",
    comparision31:
      "media/catalog/product/cache/55b9373a2aa8f64c6d5d3c78cc654110/s/p/sprint_images_yellow_colour2_14.jpg",
    comparision32:
      "media/catalog/product/cache/55b9373a2aa8f64c6d5d3c78cc654110/r/b/rbseva_legend__images_reviews__price__range__charging_time__accessories1.jpg",
    newArrival1:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/h/e/hero_vida_v1-plus_images_reviews_-price_-range_-charging-time_-accessories_.jpg",
    newArrival2:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/h/e/hero_vida_v1-pro_images_reviews_-price_-range_-charging-time_-accessories.jpg",
    newArrival3:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/3/e/3e1ca817-4bea-40ff-8f9a-7dd61ce1fea1_3.jpg",
    newArrival4:
      "media/catalog/product/cache/f4037cf015b06dc984582ea64882dd84/3/e/3e1ca817-4bea-40ff-8f9a-7dd61ce1fea1.jpg",
    guidesImage1: "media/magefan_blog/e-ashwa.jpg",
    guidesImage2: "media/magefan_blog/EVEX_INDIA.jpg",
    guidesImage3: "media/magefan_blog/motovolt.jpg",
    customerImage1: "media/wysiwyg/sonu.jpg",
    customerImage2: "media/wysiwyg/lakshay_1_.jpg",
    customerImage3: "media/wysiwyg/anuj_1_.jpg",
  };
  